version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    entrypoint: /usr/bin/entrypoint.sh
    volumes:
      - .:/kodomoapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: db
